### PR TITLE
[WIP] Include contribuition of the motor on the cm x alpha

### PR DESCRIPTION
**Pull request by gabiweis**
WIP 

The Rho on the flight stability analysis is hardcoded
Velocity from the velocity x alpha is wrong

### CODE REVIEW

**Comment by rafaellehmkuhl** [comment]
Gabi, do you want to continue working on this pull request?

If so, I think we could use the same approach as the one on performance analysis (passing analysis parameters on the parameters dictionary):


```
class Takeoff:
    def __init__(self, plane, performance_parameters):
        self.plane = plane
        self.rho_air = performance_parameters.get("rho_air")
```

What do you think?

PS: about "Velocity from the velocity x alpha is wrong", what do you think is needed?

**Comment by gabiweis** [comment]
I think it wasn't me actually that made this pull request. For the date seems it was to explain me how git hub works, maybe was Bruno?

**Comment by rafaellehmkuhl** [comment]
@bruno-szdl do you remember something about this PR?

**Comment by bruno-szdl** [comment]
I remember working on the motor contribution to the cm alpha curve, not on the alpha x velocity curve. But I don't remember making this pull request.

**Comment by rafaellehmkuhl** [comment]
It seems like this PR, although important, has no one to take care of right now. 

I will close it for now and we can reopen it once ready.

**Pull request closed without merging**
