### PR TITLE
Add test for Static Margin class

### PR DESCRIPTION
**Pull request by joaofoes**

### CODE REVIEW

**Comment by joaofoes** [comment]
Ok, so for this one i'm getting an error when the hs surface is called by the static margin class. At first i thought that the way i've called the parameters into the class was wrong, but, all the others surfaces was called into the class without any problems. Could you take a look? @rafaellehmkuhl 

Thanks in advace.

**Comment by joaofoes** [comment]
Oh and just to let it clear, this is just me testing the function, not the test itself.

**Comment by rafaellehmkuhl** [comment]
The only problem is that you are saying that the CLmax for sd7037 is 0.7, which is low and is limiting the analysis to low angles of attack.

If you put [a value of 1.5](http://airfoiltools.com/airfoil/details?airfoil=sd7037-il), the analysis runs without problems.

PS: as stated on #103 we shouldn't need to pass climax, as it is calculated internally with AVL, but as we don't know already how to get this value from there, we need to pass it.

**Comment by rafaellehmkuhl** [comment]
It seems ready to merge. Is it @joaofoes?

**Comment by joaofoes** [comment]
Yes, this one is ready to merge.

**Comment by rafaellehmkuhl** [comment]
Squashed and merged your commit @joaofoes.

PS: "Squashing" means I joined your two commits in one since they had the same goal and one was just a fix for the other.

**Pull request merged**
