### PR TITLE
Fixing cm plot

### PR DESCRIPTION
**Pull request by davidssand**
Plotting trim graph that matches XFLR5.

### CODE REVIEW

**Comment by rafaellehmkuhl** [comment]
This branch should be rebased before merged.

**Comment by rafaellehmkuhl** [comment]
Please reinsert VLM into the code

**Comment by davidssand** [comment]
image
CM_alpha do avião do ADR bem similar ao do X5.

**Comment by davidssand** [comment]
image
Static margin still not plotting well.

**Comment by rafaellehmkuhl** [comment]
Static margin for conventional is saaaaaaaad

**Comment by rafaellehmkuhl** [comment]
PR is ready to go.

Please rebase onto master and squash your commits onto clear ones.

**Comment by rafaellehmkuhl** [comment]
Static margin problem is now on #27

**Pull request merged**
